### ISSUE TITLE
Missing sentence, lemma, and form

### ISSUE THREAD

**Issue by rajaswa** [UniversalDependencies/UD_Hindi_English-HIENCS#2]
The currently available data in the repository seems to be corrupted? There is nothing but "-" at every entry for sentence, form, and lemma!

**Comment by dan-zeman** [comment]
Read the [README](https://github.com/UniversalDependencies/UD_Hindi_English-HIENCS/blob/master/README.md) file :-) The underlying text cannot be distributed directly, due to licensing restrictions.
